#!/bin/sh
conf="`dirname $0`/ectl-conf"
test -f "$conf" && . "$conf"

exec erl \
    -pa "${EBIN}" \
    -noinput \
    -hidden \
    ${CTL_ERL_ARGS} \
    -name "ctl${$}_${EXT_NODENAME}" \
    -s erpher_extra_ctl \
    -nodename $EXT_NODENAME \
    -extra "$@"
